name: "AI Code Reviewer for Pull Requests"
description: "Review, summarize and auto-fix pull requests with AI"
author: "Presubmit.ai"
branding:
  icon: "check-square"
  color: "black"

inputs:
  llm_model:
    description: "The LLM model to use for code review"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
