name: "AI Code Reviewer for Pull Requests"
description: "Review, summarize and auto-fix pull requests with AI"
author: "Presubmit.ai"
branding:
  icon: "check-square"
  color: "black"

inputs:
  enable_pr_summary:
    description: "Whether to automatically generate a summary for the PR"
    required: true
    default: true
  enable_title_generation:
    description: "Whether to automatically generate a title for PRs that mention @presubmitai. Needs enable_pr_summary to be true."
    required: true
    default: true
  enable_overview_comment:
    description: "Whether to automatically generate an overview for the PR. Needs enable_pr_summary to be true."
    required: true
    default: true
  enable_code_review:
    description: "Whether to review code changes in the PR and add comments"
    required: true
    default: true
  llm_model:
    description: "The LLM model to use for code review"
    required: true
    default: "claude-3-5-sonnet-20241022"
runs:
  using: "node20"
  main: "dist/index.js"
