name: Presubmit.ai

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.LLM_API_KEY }}" ]; then
            echo "Error: LLM_API_KEY secret is not configured"
            exit 1
          fi
      - name: Demo additional context - 1
        run: echo "- Never use ternary operator." > style_guide_1.md
      - name: Demo additional context - 2
        run: echo "- Function should always begin with a comment that describe it." > style_guide_2.md
      - uses: kingychiu/ai-reviewer@additional-context
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_MODEL: "claude-3-5-sonnet-20241022"
          REVIEW_GUIDE_FILES: "style_guide_1.md,style_guide_2.md"
